name: Doubango Build with Rocky Linux

on:
  workflow_dispatch:
    inputs:
      android_abi:
        description: 'Android ABI (armeabi-v7a, arm64-v8a, x86, x86_64)'
        required: true
        default: 'arm64-v8a'
      rocky_version:
        description: 'Rocky Linux version (8 or 9)'
        required: true
        default: '9'
      enable_debug:
        description: 'Enable debug symbols (true/false)'
        type: boolean
        default: true
      swig_version:
        description: 'SWIG version (e.g., 4.1.1)'
        required: false
        default: '4.1.1'

jobs:
  build-doubango:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:${{ github.event.inputs.rocky_version }}
      options: --user root
    
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      # 明确定义 NDK 环境变量
      ANDROID_NDK_HOME: /opt/android-sdk/ndk/21.0.6113669
      NDK: /opt/android-sdk/ndk/21.0.6113669  # NDK 别名
      DOUBANGO_SOURCE: ${{ github.workspace }}
      DOUBANGO_OUTPUT: /output
      ANDROID_ABI: ${{ github.event.inputs.android_abi }}
      ROCKY_VERSION: ${{ github.event.inputs.rocky_version }}
      ENABLE_DEBUG: ${{ github.event.inputs.enable_debug }}
      SWIG_VERSION: ${{ github.event.inputs.swig_version }}
      NDK_VERSION: "21.0.6113669"  # 固定使用此版本
    
    steps:
    - name: Checkout current repository (forked)
      uses: actions/checkout@v4
      
    - name: Print build parameters
      run: |
        echo "### 编译参数"
        echo "Android ABI: $ANDROID_ABI"
        echo "NDK Version: $NDK_VERSION"
        echo "Rocky Linux Version: $ROCKY_VERSION"
        echo "Debug Symbols: $ENABLE_DEBUG"
        echo "SWIG Version: $SWIG_VERSION"
        echo "Container OS: $(cat /etc/os-release | grep PRETTY_NAME)"
        echo "###"
        echo "Doubango source at: $DOUBANGO_SOURCE"
        echo "Android NDK HOME: $ANDROID_NDK_HOME"
        echo "NDK variable: $NDK"
        echo "Current user: $(whoami)"
      
    - name: Install system dependencies
      run: |
        dnf update -y
        dnf install -y \
          autoconf \
          automake \
          libtool \
          pkgconfig \
          make \
          gcc-c++ \
          wget \
          unzip \
          tar \
          git \
          python3 \
          python3-devel \
          glibc-langpack-en \
          java-11-openjdk-devel \
          openssl-devel
        
        # 设置语言环境
        export LANG=en_US.UTF-8
        
        # 验证安装
        autoconf --version
        automake --version
        make --version
        g++ --version
      
    - name: Install PCRE2 development package
      run: |
        # 安装PCRE2开发包（SWIG依赖）
        dnf install -y pcre2-devel
        
        # 验证PCRE2安装
        pcre2-config --version
        echo "PCRE2 development package installed"
      
    - name: Install SWIG from source
      run: |
        # 安装编译SWIG的其他依赖
        dnf install -y byacc
        
        # 下载并编译SWIG
        SWIG_VERSION="$SWIG_VERSION"
        wget https://github.com/swig/swig/archive/refs/tags/v${SWIG_VERSION}.tar.gz
        tar xzf v${SWIG_VERSION}.tar.gz
        cd swig-${SWIG_VERSION}
        
        # 配置和编译
        ./autogen.sh
        ./configure --prefix=/usr/local
        make -j$(nproc)
        make install
        
        # 验证安装
        swig -version | head -n 1
        echo "SWIG installed at $(which swig)"
      
    - name: Setup Android SDK and NDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        
        # 下载命令行工具
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        
        # 设置环境变量
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        
        # 接受许可协议
        yes | sdkmanager --licenses
        
        # 安装平台工具
        sdkmanager "platform-tools"
        
        # 安装指定版本的NDK
        sdkmanager "ndk;$NDK_VERSION"
        
        # 验证NDK安装路径
        echo "验证NDK安装路径:"
        echo "ANDROID_NDK_HOME 应为: $ANDROID_NDK_HOME"
        ls -ld $ANDROID_NDK_HOME || echo "目录尚未创建"
        
        # 确保NDK目录存在
        # mkdir -p $ANDROID_NDK_HOME
        # if [ -d "$ANDROID_SDK_ROOT/ndk/$NDK_VERSION" ]; then
        #   echo "移动NDK到预定位置"
        #   #mv $ANDROID_SDK_ROOT/ndk/$NDK_VERSION/* $ANDROID_NDK_HOME/
        # else
        #   echo "ERROR: NDK未安装在预期位置!"
        #   echo "检查NDK安装目录:"
        #   ls -lR $ANDROID_SDK_ROOT/ndk/ || true
        #   exit 1
        # fi
        
        # 验证NDK安装
        $ANDROID_NDK_HOME/ndk-build --version
        
        # 检查关键文件
        TOOLCHAIN_SCRIPT="$ANDROID_NDK_HOME/build/tools/make-standalone-toolchain.sh"
        echo "Checking for make-standalone-toolchain.sh at: $TOOLCHAIN_SCRIPT"
        
        if [ -f "$TOOLCHAIN_SCRIPT" ]; then
          echo "make-standalone-toolchain.sh found in NDK"
          chmod +x "$TOOLCHAIN_SCRIPT"  # 确保有执行权限
        else
          echo "ERROR: make-standalone-toolchain.sh not found in NDK!"
          ls -lR $ANDROID_NDK_HOME/build/tools/ || true
          exit 1
        fi
        
        # 输出NDK环境变量状态
        echo "最终NDK环境变量:"
        echo "ANDROID_NDK_HOME = $ANDROID_NDK_HOME"
        echo "NDK = $NDK"
      
    - name: Prepare NDK toolchains (Doubango compatibility fix)
      run: |
        echo "使用NDK路径: $NDK"
        # cd $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin
        # ln -sf aarch64-linux-android21-clang++ aarch64-linux-android-clang++ || true
        # ln -sf armv7a-linux-androideabi21-clang++ arm-linux-androideabi-clang++ || true
        # echo "Created NDK toolchain symlinks"
      
    - name: Configure and build Doubango
      run: |
        cd $DOUBANGO_SOURCE
        
        # 输出NDK环境变量状态
        echo "构建前NDK环境变量:"
        echo "NDK = $NDK"
        echo "ANDROID_NDK_HOME = $ANDROID_NDK_HOME"
        
        # 检查关键文件
        TOOLCHAIN_SCRIPT="$NDK/build/tools/make-standalone-toolchain.sh"
        echo "验证文件存在: $TOOLCHAIN_SCRIPT"
        ls -l "$TOOLCHAIN_SCRIPT" || true
        
        # 运行autogen脚本序列
        ./autogen.sh
        cd bindings
        ./autogen.sh
        cd ..
        
        # 执行Android构建脚本
        ./android_build.sh

        # 执行Android构建脚本并添加详细日志
        # {
        # set -x
        # ./android_build.sh \
        #   --arch $ANDROID_ABI \
        #   --api $ANDROID_API_LEVEL \
        #   --toolchain $STANDALONE_TOOLCHAIN_PATH
        # set +x
        # } 2>&1 | tee build.log
    
        # # 检查构建状态
        # if [ ${PIPESTATUS[0]} -ne 0 ]; then
        #   echo "Build failed! Showing last 100 lines of build.log:"
        #   tail -n 100 build.log
        #   exit 1
        # fi
        
        # 安装编译产物
        mkdir -p $DOUBANGO_OUTPUT
        cp -r bin/* $DOUBANGO_OUTPUT/
        
        # 验证编译结果
        find $DOUBANGO_OUTPUT -name "*.so" -o -name "*.a" | xargs -I {} ls -lh {}
        echo "Build completed successfully!"
      
    - name: Collect artifacts
      run: |
        mkdir -p /github/workspace/artifacts
        cp -r $DOUBANGO_OUTPUT/* /github/workspace/artifacts/
        
        # 创建版本信息文件
        echo "Doubango Build Report" > /github/workspace/artifacts/build-info.txt
        echo "Build Date: $(date)" >> /github/workspace/artifacts/build-info.txt
        echo "Android ABI: $ANDROID_ABI" >> /github/workspace/artifacts/build-info.txt
        echo "NDK Version: $NDK_VERSION" >> /github/workspace/artifacts/build-info.txt
        echo "Rocky Linux Version: $ROCKY_VERSION" >> /github/workspace/artifacts/build-info.txt
        echo "Debug Symbols Enabled: $ENABLE_DEBUG" >> /github/workspace/artifacts/build-info.txt
        echo "SWIG Version: $SWIG_VERSION" >> /github/workspace/artifacts/build-info.txt
        echo "PCRE2 Version: $(pcre2-config --version)" >> /github/workspace/artifacts/build-info.txt
        $ANDROID_NDK_HOME/ndk-build --version >> /github/workspace/artifacts/build-info.txt
        echo "make-standalone-toolchain.sh: $(ls -l $NDK/build/tools/make-standalone-toolchain.sh)" >> /github/workspace/artifacts/build-info.txt
        echo "NDK环境变量: $NDK" >> /github/workspace/artifacts/build-info.txt
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doubango-build-${{ github.event.inputs.android_abi }}-${{ env.NDK_VERSION }}
        path: artifacts
        retention-days: 7
      
    - name: Generate build summary
      run: |
        echo "### Doubango 编译报告" >> $GITHUB_STEP_SUMMARY
        echo "**Android ABI**: $ANDROID_ABI" >> $GITHUB_STEP_SUMMARY
        echo "**NDK 版本**: $NDK_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "**Rocky Linux 版本**: $ROCKY_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "**调试符号**: $ENABLE_DEBUG" >> $GITHUB_STEP_SUMMARY
        echo "**SWIG 版本**: $SWIG_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "**PCRE2 版本**: $(pcre2-config --version)" >> $GITHUB_STEP_SUMMARY
        echo "**编译时间**: $(date)" >> $GITHUB_STEP_SUMMARY
        
        # 检查文件是否存在并记录状态
        TOOLCHAIN_SCRIPT="$NDK/build/tools/make-standalone-toolchain.sh"
        if [ -f "$TOOLCHAIN_SCRIPT" ]; then
          echo "**make-standalone-toolchain.sh**: 存在 ($(ls -l $TOOLCHAIN_SCRIPT | awk '{print $5}') 字节)" >> $GITHUB_STEP_SUMMARY
        else
          echo "**make-standalone-toolchain.sh**: ❌ 未找到" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "#### NDK 环境变量" >> $GITHUB_STEP_SUMMARY
        echo "ANDROID_NDK_HOME = $ANDROID_NDK_HOME" >> $GITHUB_STEP_SUMMARY
        echo "NDK = $NDK" >> $GITHUB_STEP_SUMMARY
        
        echo "#### 包含的库文件" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        find artifacts -name "*.so" -o -name "*.a" | sort >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        
        echo "#### 下载产物" >> $GITHUB_STEP_SUMMARY
        echo "工作流完成后，在 Artifacts 区域下载编译结果" >> $GITHUB_STEP_SUMMARY
